
export const Categories = [
  {
    name: 'Comida',
    image: require('../assets/images/burger.png'),
    items: [
      {
        id: 1,
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 22,
        isTopOfTheWeek: true,
        image: require('../assets/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../assets/images/flour.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/Sliced-Onion.png'),
          require('../assets/images/Tomato.png'),
        ],
      },
      {
        id: 2,
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 20,
        isTopOfTheWeek: false,
        image: require('../assets/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('../assets/images/Sliced-Onion.png'),
          require('../assets/images/Tomato.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/flour.png'),
        ],
      },
      {
        id: 3,
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 29,
        isTopOfTheWeek: false,
        image: require('../assets/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../assets/images/Tomato.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/Sliced-Onion.png'),
          require('../assets/images/flour.png'),
        ],
      },
    ],
  },
  {

    name: 'Pizza',
    image: require('../assets/images/pizza.png'),
    items: [
      {
        id: 4,
        name: 'Pepperoni Pizza',
        weight: 250,
        rating: '5.0',
        price: 12,
        isTopOfTheWeek: true,
        image: require('../assets/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../assets/images/Tomato.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/Sliced-Onion.png'),
          require('../assets/images/flour.png'),
        ],
      },
      {
        id: 5,
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 30,
        isTopOfTheWeek: false,
        image: require('../assets/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../assets/images/Sliced-Onion.png'),
          require('../assets/images/flour.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/Tomato.png'),
        ],
      },
      {
        id: 6,
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.2',
        price: 45,
        isTopOfTheWeek: false,
        image: require('../assets/images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 45,
        ingredients: [
          require('../assets/images/flour.png'),
          require('../assets/images/cheese.png'),
          require('../assets/images/Tomato.png'),
          require('../assets/images/Sliced-Onion.png'),
        ],
      },
    ],
  },
  {
    name: 'Soft Drinks',
    image: require('../assets/images/softdrinks.png'),
    items: [
      {
        id: 7,
        name: 'Coco Cola',
        weight: 200,
        rating: '5.0',
        price: 3,
        isTopOfTheWeek: true,
        image: require('../assets/images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('../assets/images/softdrinks/cocacola.png')],
      },
      {
        id: 8,
        name: 'Orange Juice',
        weight: 500,
        rating: '4.5',
        price: 12,
        isTopOfTheWeek: false,
        image: require('../assets/images/softdrinks/orange.png'),
        size: 'LArge Glass',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('../assets/images/softdrinks/orange.png')],
      },
      {
        id: 9,
        name: 'Mango Juice',
        weight: 150,
        rating: '4.2',
        price: 20,
        isTopOfTheWeek: false,
        image: require('../assets/images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Small Ice',
        delivery: 5,
        ingredients: [require('../assets/images/softdrinks/mango.png')],
      },
    ],
  },
];
